version: "3.8"

networks:
  main:
    driver: bridge

services:
  backend:
    build: .
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    command: air backend/cmd/main.go
    networks:
      - main
    depends_on:
      mysql_database:
        condition: service_healthy

  mysql_database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME_DATABASE}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mysql_database --silent"]
      interval: 5s
      retries: 10
    # command: >
    #   bash -c " sleep 5;  mysql -h localhost -u admin -p${DB_PASSWORD} -e 'CREATE TABLE IF NOT EXISTS users(id int auto_increment primary key,username varchar(100) not null,nick varchar(100) not null unique,email varchar(100) not null unique,password varchar(100) not null,CreatedAt timestamp default current_timestamp()) ENGINE=INNODB;' 
    #   "
    networks:
      - main
