version: '3.8'
networks:
  main:
    driver: bridge

services:
  mysql_database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME_DATABASE}
    ports:
      - 3306:3306
    networks:
      - main

  backend:
    build: .
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    command: air backend/cmd/main.go
    networks:
      - main
    depends_on:
      - mysql_database