name: CI_WORKFLOW

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: runs_test
      uses: actions/checkout@v2
    - name: Test
      run: cd backend && - go test ./... -coverpkg=./... -coverprofile=coverage.out
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.out

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Restrict analysis to backend
        run: |
            mkdir analysis
            cp -R ./backend analysis/
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: -Dsonar.projectBaseDir=analysis